package net.sorenon.wiiuse_lwjgl;

public enum WiiuseEventType {
	WIIUSE_NONE,
	WIIUSE_EVENT,
	WIIUSE_STATUS,
	WIIUSE_CONNECT,
	WIIUSE_DISCONNECT,
	WIIUSE_UNEXPECTED_DISCONNECT,
	WIIUSE_READ_DATA,
	WIIUSE_WRITE_DATA,
	WIIUSE_NUNCHUK_INSERTED,
	WIIUSE_NUNCHUK_REMOVED,
	WIIUSE_CLASSIC_CTRL_INSERTED,
	WIIUSE_CLASSIC_CTRL_REMOVED,
	WIIUSE_GUITAR_HERO_3_CTRL_INSERTED,
	WIIUSE_GUITAR_HERO_3_CTRL_REMOVED,
	WIIUSE_WII_BOARD_CTRL_INSERTED,
	WIIUSE_WII_BOARD_CTRL_REMOVED,
	WIIUSE_MOTION_PLUS_ACTIVATED,
	WIIUSE_MOTION_PLUS_REMOVE
}
